version: '2.1'

volumes:
    mysql_volume:
    wordpress_volume:

services:
  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=${MYSQL_ROOT_PASSWORD} --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    restart: always

  wordpress:
    depends_on:
      - mysql
    container_name: wordpress
    image: wordpress
    ports:
      - 8080:80
    volumes:
      - wordpress_volume:/var/www/html
    links:
      - mysql:mysql
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  nginx-proxy:
    depends_on:
      - wordpress
    container_name: nginx-proxy
    image: jwilder/nginx-proxy:alpine
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=${VIRTUAL_HOST}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always


  wordpress-cli:
    depends_on:
      mysql:
          condition: service_healthy
      wordpress:
          condition: service_healthy
      nginx-proxy:
          condition: service_healthy
    container_name: wordpress-cli
    image: wordpress:cli
    user: xfs
    volumes:
      - wordpress_volume:/var/www/html
    links:
      - mysql:mysql
    #entrypoint: wp
    command: >
      /bin/bash -c "
        wp core install --url=\"$VIRTUAL_HOST\" --title=\"$WORDPRESS_TITLE\" --admin_user=\"$WORDPRESS_USER\" --admin_password=\"$WORDPRESS_PASSWD\" --admin_email=\"$WORDPRESS_USER_EMAIL\"; 
        wp plugin delete hello akismet 
        "
