version: '2'

volumes:
    mysql_volume:
    wordpress_volume:

services:
  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

  wordpress:
    depends_on:
      - mysql
    container_name: wordpress
    image: wordpress
    ports:
      - 8080:80
    volumes:
      - wordpress_volume:/var/www/html
    links:
      - mysql:mysql
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}

  nginx-proxy:
    depends_on:
      - wordpress
    container_name: nginx-proxy
    image: jwilder/nginx-proxy:alpine
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=${VIRTUAL_HOST}
